[project]
name = "video-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docx2txt>=0.9",
    "dotenv>=0.9.9",
    "google-genai>=1.52.0",
    "gradio-client>=2.0.1",
    "kaggle>=1.8.2",
    "langchain>=1.0.7",
    "langchain-google-community>=3.0.1",
    "langchain-google-genai>=3.0.3",
    "langgraph-api>=0.5.26",
    "langgraph-cli[inmem]>=0.4.7",
    "modal>=1.2.4",
    "pillow>=12.0.0",
    "pollinations>=4.5.1",
    "pydantic>=2.12.4",
]
